### PR TITLE
FileBasedLog: change from ints to longs

### LINKED ISSUE #178: FileBasedLog: change from ints to longs
In issue #126, ints were changed to longs for indices and terms. This was not done in `FileBasedLog`.

[1] https://github.com/belaban/jgroups-raft/issues/126

### PR DESCRIPTION
**Pull request by pruivo**
Closes #178

### CODE REVIEW

**Comment by belaban** [comment]
Thanks Pedro!

**Comment by belaban** [comment]
Looks good, perf is about the same as with ints.
Thanks!

**Comment by franz1981** [comment]
@belaban did you run on a Linux box?
Maybe requires a very good baseline performance to perceive the slowdown, if any..
@pruivo you get decent performance on tmpfs?

**Comment by belaban** [comment]
Nope, on my old and trusted Mac :-)

**Comment by pruivo** [comment]
> @pruivo you get decent performance on tmpfs?

Didn't check performance; just run the testsuite.

**Pull request merged**
