### PR TITLE
Add HdrHistogram to record latency

### PR DESCRIPTION
**Pull request by pruivo**
* All benchmarks record the latency into HdrHistogram
* New option: "-histogram /path/to/save" when set, it stores the logs
  in that folder. You can create plots from the logs with an external
  tool.

### CODE REVIEW

**Comment by pruivo** [comment]
Example for sync benchmark:
Histogram

**Comment by franz1981** [comment]
As suggested on https://github.com/belaban/jgroups-raft/pull/171#issuecomment-1118286683 if the recording of latencies happen in the single threaded I/O thread, we can just use the non-thread safe variant of HdrHistogram that's super fast actually ^^

**Comment by belaban** [comment]
Why didn't you remove `AverageMinMax` when switching to `HdrHistogram`?

**Comment by pruivo** [comment]
> As suggested on [#171 (comment)](https://github.com/belaban/jgroups-raft/pull/171#issuecomment-1118286683) if the recording of latencies happen in the single threaded I/O thread, we can just use the non-thread safe variant of HdrHistogram that's super fast actually ^^

that is true for the leader, but I don't think it is true for the followers. AFAIK, the `CompletionStage` is completed in the `REDIRECT` protocol by any thread delivering messages.

**Comment by pruivo** [comment]
> Why didn't you remove `AverageMinMax` when switching to `HdrHistogram`?

no reason, I'll remove the `AverageMinMax`

**Comment by pruivo** [comment]
update:
* Replaced `AverageMinMax` with `Histogram`

**Comment by belaban** [comment]
Nice! Thanks, @pruivo! At some point, it would be interesting to also print the percentiles... :-)

**Comment by pruivo** [comment]
You have the histogram files after the run. You can use them to plot the percentiles in a more meaningful way :)

**Comment by belaban** [comment]
Ah, ok, I take a mental note when updating the docs...

**Pull request merged**
