### PR TITLE
Non-blocking API for RAFT counter

### PR DESCRIPTION
**Pull request by pruivo**
The new API is not released yet. This PR is here to be available when the new version of the non-blocking counter API is available.

### CODE REVIEW

**Review by franz1981 — APPROVED** [review]
Well done Pedro ☺️
Cannot wait to see the perf counter benchmark updated while including the option to pack more async counters ops per thread; we will get some interesting ways to stress test it 👍

**Comment by belaban** [comment]
@pruivo Assuming that the code in `CounterPerf` will be changed to
```
long start=System.nanoTime();
counter.addAndGet(delta)
    .thenAccept(__ -> {
        long incr_time=System.nanoTime()-start;
        avg_updatetime.add(incr_time);
        num_updates++;
   });
```
, then - when you run `CounterPerf` for a while - `COUNTER.pending_requests` will keep growing, as requests are produced faster than processes. Are you going to install some flow control mechanism, e.g. making `pending_requests` bounded, ie. blocking updater threads when the map is full? Or will you rely on JGroups' flow control entirely?

**Comment by belaban** [comment]
@pruivo I suggest copy `Counter`, `SyncCounter` and `AsyncCounter` from your PR to JGroups into jgroups-raft and amend this PR. I think this is better because you can make changes to the interfaces as you see fit. When you're at the point where no more changes need to be made, the changes can be copied back to JGroups, and  - once 5.2.3 is released - the local interfaces can be removed.

**Comment by franz1981** [comment]
@pruivo sending soon a snippet of code that impl the load generator with some shared credits notion :+1:

**Comment by franz1981** [comment]
This is the async updater worker:
```java
    protected class AsyncUpdater implements Runnable {
        private final CountDownLatch latch;
        private long                 num_updates;
        private final AverageMinMax  avg_updatetime=new AverageMinMax(); // in ns
        private final AtomicBoolean  idle=new AtomicBoolean(false);
        private final AtomicLong     availableCredits;
        private volatile boolean     running=true;
        private final Executor       executor;

        private final Runnable wakeupIdleUpdaters;
        public AsyncUpdater(CountDownLatch latch, AtomicLong availableCredits, Executor executor, Runnable wakeupIdleUpdaters) {
            this.latch=latch;
            this.availableCredits=availableCredits;
            this.executor=executor;
            this.wakeupIdleUpdaters =wakeupIdleUpdaters;
        }

        public long          numUpdates()       {return num_updates;}
        public AverageMinMax avgUpdateTime()    {return avg_updatetime;}
        public void          stop()             {running=false;}

        public void run() {
            assert !idle.get();
            try {
                latch.await();
            }
            catch(InterruptedException e) {
                e.printStackTrace();
            }
            final AtomicLong availableCredits = this.availableCredits;
            final AtomicBoolean idle = this.idle;
            for(;;) {
                if (!running) {
                    // if !idle it won't be re-scheduled anymore
                    return;
                }
                // try acquire a single credit
                long credits;
                do {
                    credits = availableCredits.get();
                    if (credits == 0) {
                        // no credits: let's go idle
                        idle.set(true);
                        return;
                    }
                } while (!availableCredits.compareAndSet(credits, credits - 1));
                final int delta = getDelta();
                final long start = System.nanoTime();
                counter.addAndGet(delta).thenAccept(ignore -> {
                    long incr_time = System.nanoTime() - start;
                    avg_updatetime.add(incr_time);
                    num_updates++;
                    if (availableCredits.getAndIncrement() == 0) {
                        wakeupIdleUpdaters.run();
                    }
                });
            }
        }

        public void wakeup() {
            if (idle.compareAndSet(true, false)) {
                executor.execute(this);
            }
        }
    }
```
This is to start the benchmark
```java
    public UpdateResult startTest() throws Throwable {
        System.out.printf("running for %d seconds\n", time);
        final CountDownLatch latch=new CountDownLatch(1);
        counter=counter_service.getOrCreateCounter("counter", 0);
        AtomicLong availableCredits = new AtomicLong(max_concurrent_updates);
        AsyncUpdater[] updaters=new AsyncUpdater[num_threads];
        ForkJoinPool threads=new ForkJoinPool(num_threads);
        Runnable wakeupIdleUpdates = () -> {
            for (AsyncUpdater updater : updaters) {
                updater.wakeup();
            }
        };
        for(int i=0; i < num_threads; i++) {
            updaters[i]=new AsyncUpdater(latch, availableCredits, threads, wakeupIdleUpdates);
            threads.execute(updaters[i]);    
        }
        latch.countDown();
        // ...
```

**Comment by pruivo** [comment]
> @pruivo I suggest copy `Counter`, `SyncCounter` and `AsyncCounter` from your PR to JGroups into jgroups-raft and amend this PR. I think this is better because you can make changes to the interfaces as you see fit. When you're at the point where no more changes need to be made, the 'final' interfaces can be copied back to JGroups, and - once 5.2.3 is released - the local interfaces can be removed. This avoids having to release a new version of JGroups (or using snapshots) every time you make changes to the interfaces.

@belaban Copied the new API from JGroups

**Comment by belaban** [comment]
> ```java
> private CompletionStage<Long> doReq() {
>   if stop; then return
>   start timer
>   return counter.addAndGet(delta).thenCompose(__ -> stop timer ; return doReq())
> }
> List<CompletionStage> reqs = ...
> for i in [ 0 .. number of threads ]
>    reqs.append(doReq())
> sleep(test duration)
> stop = true
> for req in reqs do wait()
> ```
> 
> This way, you have a test generating `number of threads` requests in parallel.
> 
> I don't have any experience in async benchmarking, but I think it should keep a similar semantics to the current benchmark code.

The problem here is that you limit yourself to the speed of a round-trip before submitting the next `addAndGet()` call. I'm not very familiar with CompletionStages, but IIRC `thenCompose()` waits for the result until chaining a new completion stage.
I guess we can safely run as many of these operations, as JGroups' flow control will ensure that the sender gets blocked when too many requests are in-flight. In [1], the completion stage is added to the hashmap, but the `sendRequest()` method might block on flow control, so this should be ok.

[1] https://github.com/belaban/JGroups/blob/master/src/org/jgroups/protocols/COUNTER.java#L609

**Comment by belaban** [comment]
@franz1981 By all due respect, sorry, but this code is ugly! :-) Dealing with credits should not be something that should be done at the application level. I like Pedro's solution much more, but IMO we can simply invoke as many completion stages as we want: JGroups will block the sender if too many credits are exhausted and the followers cannot re-furnish them in time.
I'll look at Pedro's PR today, so we can start experimenting with an async `CounterPerf`.

**Comment by belaban** [comment]
@pruivo Do you intend to add more async tests to `CounterTest`?

**Comment by belaban** [comment]
New ticket for tests, please.

**Comment by pruivo** [comment]
@belaban what tests do you want? Note that current tests test all methods.

**Comment by franz1981** [comment]
@belaban 
> By all due respect, sorry, but this code is ugly! 

Actor-like code that implement non-blocking back-pressure is not very nice (see https://gist.github.com/viktorklang/2557678 original idea - author of Akka)

> JGroups will block the sender if too many credits are exhausted and the followers cannot re-furnish them in time

This can still work as long it can be disabled or if it can provide listeners/hook/custom strategy to let the user decide what to do
eg the load generator I've built has 2 nice properties:
- given that he manage the backpressure state himself: he can observe/measure when it happens, and report it
- it won't block the event loop thread: meaning that in theory we could pack many counter(s) load generator in the same thread, if we want 

The former, IMO, is a key feature if you still prefer letting jgroups to do it,
while the latter is a nice feature for users that don't want their caller thread to be blocked (quarkus event loop threads?) and prefer just be notified when they can further push much load.

**Comment by belaban** [comment]
@pruivo Does it test the async methods? Perhaps I need to git pull...

**Comment by pruivo** [comment]
@belaban the `SyncCounter` uses the `AsyncCounter` methods
https://github.com/belaban/jgroups-raft/blob/a99bc9009a69621777735328008ce9989b53aeb2/src/org/jgroups/raft/blocks/AsyncCounterImpl.java#L73-L104

**Comment by pruivo** [comment]
> IMO tests always also document how to use a class.

fair enough :)

**Pull request merged**
