### PR TITLE
ArrayRingBuffer's LogCache is using the wrong constructor (#141)

### PR DESCRIPTION
**Pull request by franz1981**

### CODE REVIEW

**Comment by franz1981** [comment]
Please @belaban check if the ring buffer creation is correct ie it's using the commit index as the first (possibly) cached entry index .

**Comment by belaban** [comment]
This changed performance dramatically!! Thanks!

**Comment by belaban** [comment]
However, this is new:
```
7:27:11,392  [ERROR] RAFT: C: failed applying snapshot from A: java.lang.IllegalStateException
java.lang.IllegalStateException: null
	at org.jgroups.raft.filelog.LogEntryStorage.write(LogEntryStorage.java:108) ~[classes/:?]
	at org.jgroups.protocols.raft.FileBasedLog.append(FileBasedLog.java:174) ~[classes/:?]
	at org.jgroups.raft.util.LogCache.append(LogCache.java:104) ~[classes/:?]
	at org.jgroups.protocols.raft.Follower.handleInstallSnapshotRequest(Follower.java:40) ~[classes/:?]
	at org.jgroups.protocols.raft.RAFT.handleUpRequest(RAFT.java:718) ~[classes/:?]
	at org.jgroups.protocols.raft.RAFT.process(RAFT.java:755) ~[classes/:?]
	at org.jgroups.protocols.raft.RAFT.processQueue(RAFT.java:743) ~[classes/:?]
	at org.jgroups.util.Runner.run(Runner.java:80) [jgroups-5.2.2.Final.jar:5.2.2.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by franz1981** [comment]
No idea about this behaviour, what happen while doing it on master before the log cache changes?

**Comment by franz1981** [comment]
@belaban I've verified that the issue was already present on 6177d18183967d473c41474b4992b8c49e798346 so @pruivo maybe got some idea what's going on

**Comment by pruivo** [comment]
It seems `FileBasedLog` is not aware that it receives state and expects entry with `index=1`.
I'll have to look at the code but it looks like we are missing a test for file-log when a node starts empty and receives the snapshot.

**Pull request merged**
