### PR TITLE
JCtools mpsc lock-free array-based process queue

### PR DESCRIPTION
**Pull request by franz1981**
This is still in draft because of https://github.com/belaban/jgroups-raft/issues/157; with fixing it I cannot understand if there's any issue introduced by this

### CODE REVIEW

**Comment by belaban** [comment]
@franz1981 I guess this makes the first part of https://github.com/belaban/jgroups-raft/pull/154 moot? Should we close #154  then? I'll review this today

**Comment by belaban** [comment]
Which kind of errors? I ran a couple of tests and did *not* get any!

**Comment by franz1981** [comment]
I've run it using file based log with 32 threads (with a 64 cores machine), no fsync, and with tmpfs, 120 duration run.
After few runs, it has breaks emitting this (on the leader)
```java
22:16:29.196 [runner-1] ERROR org.jgroups.protocols.raft.RAFT - A: failed handling request UpRequest AppendEntriesResponse: current_term=1, result: false (FAIL_ENTRY_NOT_FOUND), index=6217735, commit-index=6217735: java.lang.AssertionError: commit-index=6217796, match-index=6217828, next-index=6217736 [send-single-msg]
java.lang.AssertionError: commit-index=6217796, match-index=6217828, next-index=6217736 [send-single-msg]
	at org.jgroups.raft.util.CommitTable$Entry.assertInvariant(CommitTable.java:110) ~[classes/:?]
	at org.jgroups.raft.util.CommitTable.update(CommitTable.java:50) ~[classes/:?]
	at org.jgroups.raft.util.CommitTable.update(CommitTable.java:38) ~[classes/:?]
	at org.jgroups.protocols.raft.Leader.handleAppendEntriesResponse(Leader.java:54) ~[classes/:?]
	at org.jgroups.protocols.raft.RAFT.handleUpRequest(RAFT.java:748) ~[classes/:?]
	at org.jgroups.protocols.raft.RAFT.process(RAFT.java:827) ~[classes/:?]
	at org.jgroups.protocols.raft.RAFT.processQueue(RAFT.java:809) ~[classes/:?]
	at org.jgroups.util.Runner.run(Runner.java:80) [jgroups-5.2.2.Final.jar:5.2.2.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]

```
if I use master I won't get it

**Comment by belaban** [comment]
OK, reverting...

**Comment by franz1981** [comment]
It's weird he? 
consider that I cannot see what this could be done wrong -> but I can improve the existing code by saving the AtomicXYX allocation on the hot path and incrementAndGet, at least ;)
Just minor things, but worthy

**Pull request merged**
