### PR TITLE
RequestTable skip list can be replaced by ArrayRingBuffer (#138)

### PR DESCRIPTION
**Pull request by franz1981**
Please take a look here: I'm not sure if the constrains I'm enforcing here are ok although all tests are passing.

The ring buffer is lazily initialized in order to cover for the reload (on crash) use case (and test): if a ring buffer with head == 1 is used regardless what's the expected index range, committing won't be able to deque from the last added entry and would fail to remove its request.

### CODE REVIEW

**Comment by belaban** [comment]
I get 15 failures when applying this PR: run `ant all-tests reports` to see them. I'll look into this later, need to understand `ArrayRingBuffer` first. I'll probably go through `ArrayRingBufferTest` to see how it works

**Comment by franz1981** [comment]
Another not on ring-buffer: given that it accept gaps (unless the user check that it won't happen), size is not the actual number of non-null elements, but just the number of slots occupied (with elements + gaps).
I can implement it differently to help matching the actual content

**Comment by belaban** [comment]
I don't think that elements will be appended with gaps, but I think a (more) natural semantics for `size()` would be the actual non-null elements.

**Comment by franz1981** [comment]
> I don't think that elements will be appended with gaps, but I think a (more) natural semantics for size() would be the actual non-null elements.

We can do in 2 different ways:
- if the array buffer doesn't allow gaps ever, the size can be as simple as it is now
- if the array buffer allow gaps, size/set/add/remove need to be a bit more complicated to count number of gaps added/removed

I think the former is a better option TBH, but I don't know if it matches the other ring buffer usage (`LogCache`); any idea?

**Comment by belaban** [comment]
I think a major problem is that `RequestTable.isCommitted(idx)` (calling `ArrayRingBuffer.get(index)`) throws an exception when `idx > tailSequence`. However, my code at [1] probes until it finds an uncommitted entry. So, instead of throwing an exception, `isCommitted()` should return false when finding an entry that's null. IMO, `ArrayRingBuffer.get()` should return null if an element is not found (same semantics as the skiplist map used before)...

[1] https://github.com/belaban/jgroups-raft/blob/master/src/org/jgroups/protocols/raft/RAFT.java#L713

**Comment by belaban** [comment]
IMO, `ArrayRingBuffer` needs to have the *same exact semantics* as `ConcurrentSkipListMap`, so replacement is simple. If you want a `get()` that throws an exception, I suggest introduce an additional `validatingGet()`. However, I don't think this is needed

**Comment by belaban** [comment]
With a (stupid :-)) change such as the one below, all tests PASS:
```
 public boolean isCommitted(int index) {
        if (requests == null) {
            return false;
        }
        if (index < requests.getHeadSequence()) {
            return true;
        }

        Entry<?> entry = null;

        try {
            entry=requests.get(index);
        }
        catch(Throwable t) {
            
        }
        return entry != null && entry.committed;
    }
```

**Comment by franz1981** [comment]
@belaban right now there's a contains that help checking against head/tail boundaries and perform the get: I didn't throw exception so far on get with null element(s) because you won't get any exception by getting a null element from a map (either)

**Comment by franz1981** [comment]
@belaban try checking requests::contains before the `get`

**Comment by belaban** [comment]
Hmm... you're changing semantics in a couple of places, e.g.  in `RequestTable.notifyAndRemove()`, you're expecting the *first* element to be removed, otherwise you throw an exception.
This is _not_ the semantics I used to have in `RequestTable`, and I expect this to break code I have in mind when notifying client via `stream().parallel()`...

**Comment by belaban** [comment]
OK, so here's what I'll do: I'll change the code regarding `RequestTable` in this PR, but leave the code in `ArrayRingBuffer` as is, for future changes. OK?

**Comment by belaban** [comment]
I changed RequestTable, but also had to add a `remove()` to `ArrayRingBuffer`. I'll commit, so we can have the discussion on the latter on a separate (new?) issue. Note that `ArrayRingBuffer.size()` still needs to be implemented, I'll create a new issue

**Pull request closed without merging**
